## SCRAPING

In [1]:
import pandas as pd
from datetime import datetime
import extraer as ex
import asyncio
import requests as req
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
from webdriver_manager.chrome import ChromeDriverManager
from tqdm.notebook import tqdm
from selenium.webdriver.chrome.options import Options
from joblib import Parallel, delayed
import requests as req
from bs4 import BeautifulSoup as bs 
# opciones del driver
opciones=Options()

# quita la bandera de ser robot
opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
opciones.add_experimental_option('useAutomationExtension', False)
opciones.headless=False    # si True, no aperece la ventana (headless=no visible)
opciones.add_argument('--start-maximized')         # comienza maximizado

# guardar las cookies
#opciones.add_argument('user-data-dir=selenium')    # mantiene las coockies

import warnings
warnings.filterwarnings('ignore')  #Quitar prints de warnings

pd.set_option('display.max_columns', None) #Imprimir todas las columnas

### PARTIDOS

In [2]:
ex.scraping_matches()

Downloading data for Season 2022
Downloading data for Season 2021
Downloading data for Season 2020
Downloading data for Season 2019
Downloading data for Season 2018
Downloading data for Season 2017
Downloading data for Season 2016
Downloading data for Season 2015
Downloading data for Season 2014
Downloading data for Season 2013
Downloading data for Season 2012
Downloading data for Season 2011
Downloading data for Season 2010
Downloading data for Season 2009
Downloading data for Season 2008
Downloading data for Season 2007
Downloading data for Season 2006
Downloading data for Season 2005
Defining list of all seasons
Concatenating all data into one dataframe
Saving csv
File Saved

In [3]:
ex.db_concat.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,Season,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,LBH,LBD,LBA,SJH,SJD,SJA,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA,Unnamed: 58,Unnamed: 59,Unnamed: 60
0,SP1,12/08/2022,20:00,Osasuna,Sevilla,2.0,1.0,H,1.0,1.0,D,12.0,10.0,5.0,3.0,16.0,9.0,5.0,2.0,5.0,3.0,0.0,0.0,3.20,3.10,2.40,3.20,3.00,2.40,3.20,3.05,2.45,3.38,3.10,2.48,3.20,3.0,2.40,3.25,3.10,2.40,3.41,3.24,2.49,3.28,3.08,2.43,2.62,1.50,2.55,1.57,2.62,1.60,2.50,1.54,0.25,1.83,2.07,1.85,2.09,1.87,2.09,1.82,2.04,3.10,3.1,2.55,3.10,2.95,2.50,3.15,3.05,2.45,3.19,3.06,2.63,3.25,2.90,2.45,3.10,3.0,2.55,3.52,3.14,2.66,3.20,3.04,2.50,2.62,1.50,2.63,1.54,2.69,1.57,2.55,1.52,0.25,1.73,2.08,1.76,2.20,1.88,2.23,1.79,2.09,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,13/08/2022,16:00,Celta,Espanol,2.0,2.0,D,1.0,0.0,H,8.0,10.0,3.0,2.0,17.0,15.0,3.0,3.0,5.0,2.0,0.0,0.0,1.80,3.75,4.75,1.83,3.60,4.33,1.83,3.55,4.60,1.81,3.75,4.87,1.83,3.5,4.33,1.75,3.50,4.50,1.90,3.77,4.90,1.83,3.68,4.50,2.00,1.80,2.10,1.81,2.13,1.87,2.04,1.80,-0.50,1.77,2.02,1.80,2.13,1.86,2.13,1.81,2.05,1.72,3.6,4.75,1.75,3.50,5.00,1.77,3.50,5.00,1.78,3.62,5.39,1.75,3.50,5.00,1.75,3.6,5.00,1.84,3.73,5.39,1.78,3.58,5.00,2.20,1.66,2.24,1.71,2.26,1.83,2.19,1.70,-0.75,2.00,1.90,2.02,1.91,2.06,1.93,2.01,1.86,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,13/08/2022,18:00,Valladolid,Villarreal,0.0,3.0,A,0.0,0.0,D,12.0,10.0,6.0,4.0,6.0,10.0,4.0,5.0,1.0,0.0,0.0,0.0,3.90,3.60,1.90,3.80,3.50,1.95,3.85,3.60,1.95,4.05,3.78,1.95,3.90,3.5,1.95,3.80,3.50,1.90,4.10,3.80,2.00,3.93,3.66,1.94,1.99,1.91,2.00,1.91,2.00,1.92,1.95,1.87,0.50,1.95,1.95,1.97,1.95,1.97,1.98,1.93,1.93,3.30,3.4,2.20,4.00,3.40,1.95,3.35,3.35,2.20,3.54,3.44,2.23,3.50,3.25,2.15,3.40,3.4,2.20,3.66,3.47,2.25,3.45,3.39,2.19,2.00,1.80,2.09,1.81,2.14,1.90,2.05,1.79,0.25,2.02,1.88,2.02,1.91,2.03,1.91,1.98,1.88,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,13/08/2022,20:00,Barcelona,Vallecano,0.0,0.0,D,0.0,0.0,D,21.0,4.0,6.0,2.0,16.0,14.0,8.0,0.0,3.0,6.0,1.0,0.0,1.22,7.00,12.00,1.21,6.75,13.50,1.22,6.75,13.00,1.22,6.83,15.00,1.18,6.5,17.00,1.18,6.50,13.00,1.24,7.40,17.00,1.21,6.79,14.20,1.53,2.50,1.55,2.57,1.55,2.73,1.50,2.58,-2.00,2.09,1.81,2.15,1.78,2.16,1.88,2.04,1.83,1.22,6.5,12.00,1.25,6.25,11.00,1.22,6.50,12.00,1.24,6.80,13.50,1.20,6.50,15.00,1.20,7.0,13.00,1.25,7.40,16.75,1.22,6.82,13.42,1.50,2.62,1.51,2.68,1.58,2.79,1.50,2.61,-1.75,1.82,2.08,1.83,2.08,1.86,2.14,1.82,2.06,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,14/08/2022,16:30,Cadiz,Sociedad,0.0,1.0,A,0.0,1.0,A,7.0,15.0,2.0,7.0,9.0,20.0,3.0,6.0,4.0,2.0,0.0,0.0,3.60,3.20,2.20,3.40,3.20,2.20,3.45,3.20,2.20,3.62,3.29,2.26,3.40,3.2,2.20,3.50,3.13,2.15,3.75,3.33,2.26,3.55,3.24,2.20,2.37,1.57,2.50,1.59,2.50,1.65,2.38,1.59,0.25,1.99,1.91,2.00,1.93,2.05,1.93,1.98,1.87,3.80,3.0,2.15,3.70,3.00,2.20,3.65,3.05,2.25,4.03,3.08,2.22,3.90,3.00,2.15,3.75,3.1,2.20,4.05,3.18,2.25,3.80,3.07,2.20,2.62,1.50,2.74,1.51,2.75,1.55,2.61,1.50,0.25,2.05,1.85,2.06,1.87,2.08,1.92,2.00,1.86,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ex.db_concat.tail()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,Season,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,LBH,LBD,LBA,SJH,SJD,SJA,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA,Unnamed: 58,Unnamed: 59,Unnamed: 60
14672,SP2,17/06/06,NaN,Sp Gijon,Murcia,1.0,0.0,H,0.0,0.0,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.75,3.75,1.85,2.85,4.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.10,2.65,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56,22.0,2.10,2.03,2.92,2.78,4.00,3.71,5.0,1.98,1.97,1.86,1.86,6.0,-0.25,1.87,1.85,2.02,2.00,NaN,NaN,NaN,2.00,2.62,4.00,2.05,2.80,3.55,NaN,NaN,NaN,2.10,2.80,3.60,NaN,NaN,NaN
14673,SP2,17/06/06,NaN,Tenerife,Albacete,1.0,1.0,D,0.0,0.0,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.10,2.75,3.50,2.00,2.70,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.95,2.90,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56,22.0,2.10,2.05,2.90,2.77,4.25,3.70,6.0,1.91,1.88,1.95,1.94,6.0,-0.25,1.81,1.80,2.05,2.05,NaN,NaN,NaN,2.10,2.75,3.50,2.05,2.75,3.60,NaN,NaN,NaN,2.10,2.80,3.60,NaN,NaN,NaN
14674,SP2,17/06/06,NaN,Valladolid,Elche,2.0,2.0,D,0.0,2.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.87,3.60,1.95,2.85,3.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.90,3.10,3.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56,22.0,2.00,1.95,3.10,2.87,4.33,3.88,5.0,1.91,1.88,1.95,1.94,6.0,-0.5,2.09,2.06,1.84,1.81,NaN,NaN,NaN,1.91,2.75,4.33,1.95,2.85,3.80,NaN,NaN,NaN,2.00,2.88,3.75,NaN,NaN,NaN
14675,SP2,17/06/06,NaN,Xerez,Malaga B,4.0,2.0,H,4.0,1.0,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.61,3.25,5.00,1.65,3.30,4.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.53,3.50,5.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56,22.0,1.68,1.61,3.50,3.31,6.00,5.16,8.0,1.97,1.90,1.95,1.92,6.0,-0.75,1.77,1.77,2.11,2.09,NaN,NaN,NaN,1.50,3.50,6.00,1.60,3.30,5.00,NaN,NaN,NaN,1.62,3.20,5.50,NaN,NaN,NaN
14676,SP2,18/06/06,NaN,Hercules,Recreativo,0.0,2.0,A,0.0,2.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.75,2.75,2.50,2.85,2.70,2.50,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.9,2.25,3.00,2.70,2.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56,20.0,3.00,2.81,3.00,2.78,2.60,2.47,5.0,1.85,1.84,2.00,1.99,4.0,0.0,2.10,2.09,1.78,1.76,NaN,NaN,NaN,2.75,3.00,2.38,2.80,2.75,2.45,NaN,NaN,NaN,3.00,2.75,2.40,NaN,NaN,NaN

In [5]:
ex.db_concat.shape

(14677, 142)

### TEAMS

In [6]:
teams_stats = ['https://fbref.com/en/comps/12/stats/La-Liga-Stats',
               'https://fbref.com/en/comps/17/stats/Segunda-Division-Stats']

In [7]:
lst_df=Parallel(n_jobs=6, verbose=True)(delayed(ex.scraping_teams)(url) for url in tqdm(teams_stats))

  0%|          | 0/2 [00:00<?, ?it/s]

[Parallel(n_jobs=6)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=6)]: Done   2 out of   2 | elapsed:  1.0min finished

In [8]:
len(lst_df)

2

In [9]:
lst_df[0].columns

Index(['Squad', '# Pl', 'Age', 'Poss', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast', 'G+A',
       'G-PK', 'G+A-PK', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'xG', 'xAG',
       'xG+xAG', 'npxG', 'npxG+xAG'],
      dtype='object')

In [10]:
lst_df[0] = lst_df[0].drop(['xG', 'npxG', 'xAG', 'npxG+xAG', 'xG', 'xAG', 'xG+xAG', 'npxG', 'npxG+xAG'], axis=1)

In [11]:
lst_df[1]

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
0,Alavés,23,26.8,44.1,20,220,"1,800",20.0,21,11,19,2,3,48,5,1.05,0.55,1.60,0.95,1.50
1,Albacete,25,27.1,49.0,20,220,"1,800",20.0,23,13,20,3,4,48,5,1.15,0.65,1.80,1.00,1.65
2,Andorra,26,25.7,66.4,20,220,"1,800",20.0,21,16,19,2,2,31,4,1.05,0.80,1.85,0.95,1.75
3,Burgos,23,27.3,41.7,20,220,"1,800",20.0,18,16,17,1,1,44,4,0.90,0.80,1.70,0.85,1.65
4,Cartagena,26,31.0,53.3,20,220,"1,800",20.0,23,14,18,5,6,51,3,1.15,0.70,1.85,0.90,1.60
5,CD Mirandés,24,24.1,49.1,20,220,"1,800",20.0,23,18,21,2,2,38,3,1.15,0.90,2.05,1.05,1.95
6,Eibar,23,28.4,54.6,20,220,"1,800",20.0,23,16,19,4,5,60,4,1.15,0.80,1.95,0.95,1.75
7,Granada,26,28.8,55.7,20,220,"1,800",20.0,22,16,20,2,3,46,2,1.10,0.80,1.90,1.00,1.80
8,Huesca,27,28.4,41.6,20,220,"1,800",20.0,15,10,12,3,3,50,4,0.75,0.50,1.25,0.60,1.10
9,Las Palmas,25,26.5,65.0,20,220,"1,800",20.0,22,19,20,2,2,48,1,1.10,0.95,2.05,1.00,1.95
10,Leganés,25,29.4,52.2,20,220,"1,800",20.0,20,16,19,1,1,57,2,1.00,0.80,1.80,0.95,1.75
11,Levante,25,27.7,52.3,20,220,"1,800",20.0,22,11,18,4,4,66,3,1.10,0.55,1.65,0.90,1.45
12,Lugo,24,27.6,41.8,20,220,"1,800",20.0,17,10,15,2,3,55,4,0.85,0.50,1.35,0.75,1.25
13,Málaga,31,30.1,51.9,20,220,"1,800",20.0,14,7,14,0,1,50,3,0.70,0.35,1.05,0.70,1.05
14,Oviedo,26,27.8,43.4,20,220,"1,800",20.0,12,6,9,3,4,49,2,0.60,0.30,0.90,0.45,0.75
15,Ponferradina,28,27.9,51.9,20,220,"1,800",20.0,19,15,17,2,2,66,1,0.95,0.75,1.70,0.85,1.60
16,Racing Sant,26,27.0,40.9,20,220,"1,800",20.0,8,4,8,0,2,46,9,0.40,0.20,0.60,0.40,0.60
17,Sporting Gijón,28,27.7,45.7,20,220,"1,800",20.0,22,13,21,1,1,47,1,1.10,0.65,1.75,1.05,1.70
18,Tenerife,29,28.5,47.0,20,220,"1,800",20.0,21,13,17,4,5,52,4,1.05,0.65,1.70,0.85,1.50
19,UD Ibiza,26,26.7,47.1,20,220,"1,800",20.0,13,9,11,2,2,61,4,0.65,0.45,1.10,0.55,1.00
20,Villarreal B,27,22.4,51.4,20,220,"1,800",20.0,23,16,21,2,3,52,3,1.15,0.80,1.95,1.05,1.85
21,Zaragoza,28,27.1,55.0,20,220,"1,800",20.0,16,12,15,1,1,48,3,0.80,0.60,1.40,0.75,1.35

In [12]:
df_teams = pd.concat(lst_df)
df_teams.head()

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
0,Almería,26,26.6,45.1,14,154,"1,260",14.0,16,12,16,0,0,47,3,1.14,0.86,2.00,1.14,2.00
1,Athletic Club,25,28.0,52.4,14,154,"1,260",14.0,23,17,21,2,3,23,1,1.64,1.21,2.86,1.50,2.71
2,Atlético Madrid,23,29.1,49.8,14,154,"1,260",14.0,20,16,20,0,0,43,2,1.43,1.14,2.57,1.43,2.57
3,Barcelona,25,26.6,64.3,14,154,"1,260",14.0,33,23,33,0,1,33,3,2.36,1.64,4.00,2.36,4.00
4,Betis,27,28.9,50.1,14,154,"1,260",14.0,16,9,13,3,3,33,7,1.14,0.64,1.79,0.93,1.57

In [13]:
df_teams.reset_index(drop=True, inplace=True)
df_teams.tail()

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
37,Sporting Gijón,28,27.7,45.7,20,220,"1,800",20.0,22,13,21,1,1,47,1,1.10,0.65,1.75,1.05,1.70
38,Tenerife,29,28.5,47.0,20,220,"1,800",20.0,21,13,17,4,5,52,4,1.05,0.65,1.70,0.85,1.50
39,UD Ibiza,26,26.7,47.1,20,220,"1,800",20.0,13,9,11,2,2,61,4,0.65,0.45,1.10,0.55,1.00
40,Villarreal B,27,22.4,51.4,20,220,"1,800",20.0,23,16,21,2,3,52,3,1.15,0.80,1.95,1.05,1.85
41,Zaragoza,28,27.1,55.0,20,220,"1,800",20.0,16,12,15,1,1,48,3,0.80,0.60,1.40,0.75,1.35

In [14]:
print("Saving csv")
df_teams.to_csv(r'../data/teams.csv')
print("File Saved")

Saving csv
File Saved

### JUGADORES

In [15]:
datos2 = []

In [17]:
lst_df = Parallel(n_jobs=6, verbose=True)(delayed(ex.scraping_players)(url) for url in tqdm(teams_stats))

  0%|          | 0/2 [00:00<?, ?it/s]

[Parallel(n_jobs=6)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=6)]: Done   2 out of   2 | elapsed: 22.4min finished

In [18]:
lst_df[0].head()

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK,xG,npxG,xAG,npxG+xAG,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches
0,1,Marcos Acuña,ar ARG,DF,Sevilla,31-047,1991,10,7,551,6.1,0,0,0,0,0,4,1,0.00,0.00,0.00,0.00,0.00,0.3,0.3,1.1,1.4,0.05,0.17,0.22,0.05,0.22,Matches
1,2,Álvaro Aguado,es ESP,MF,Valladolid,26-227,1996,13,8,747,8.3,0,2,0,0,0,1,0,0.00,0.24,0.24,0.00,0.24,0.2,0.2,0.9,1.1,0.03,0.10,0.13,0.03,0.13,Matches
2,3,Joseph Aidoo,gh GHA,DF,Celta Vigo,27-076,1995,14,14,"1,260",14.0,1,0,1,0,0,2,0,0.07,0.00,0.07,0.07,0.07,0.5,0.5,0.0,0.5,0.03,0.00,0.04,0.03,0.04,Matches
3,4,Sergio Akieme,es ESP,DF,Almería,24-363,1997,14,14,"1,260",14.0,0,0,0,0,0,3,0,0.00,0.00,0.00,0.00,0.00,0.9,0.9,0.7,1.6,0.07,0.05,0.11,0.07,0.11,Matches
4,5,Paul Akouokou,ci CIV,MF,Betis,24-359,1997,6,2,238,2.6,0,0,0,0,0,2,0,0.00,0.00,0.00,0.00,0.00,0.1,0.1,0.0,0.1,0.04,0.00,0.04,0.04,0.04,Matches

In [19]:
lst_df[0].columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
       'Gls', 'Ast', 'G+A', 'G-PK', 'G+A-PK', 'xG', 'npxG', 'xAG', 'npxG+xAG',
       'xG', 'xAG', 'xG+xAG', 'npxG', 'npxG+xAG', 'Matches'],
      dtype='object')

In [20]:
lst_df[0] = lst_df[0].drop(['xG', 'npxG', 'xAG', 'npxG+xAG', 'xG', 'xAG', 'xG+xAG', 'npxG', 'npxG+xAG', 'Matches'], axis=1)

In [21]:
lst_df[1].head()

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK,Matches
0,1,Haitam Abaida,ma MAR,MF,Málaga,20-196,2002,4,1,103,1.1,1,0,1,0,0,0,0,0.87,0.00,0.87,0.87,0.87,Matches
1,2,Sabit Abdulai,gh GHA,"MF,DF",Ponferradina,23-217,1999,14,7,607,6.7,0,1,0,0,0,4,0,0.00,0.15,0.15,0.00,0.15,Matches
2,3,Amir Abedzadeh,ir IRN,GK,Ponferradina,29-232,1993,13,13,"1,170",13.0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches
3,4,Abel,es ESP,"MF,DF",Oviedo,22-115,2000,18,11,"1,047",11.6,0,0,0,0,0,2,0,0.00,0.00,0.00,0.00,0.00,Matches
4,5,Abdelkabir Abqar,ma MAR,DF,Alavés,23-279,1999,18,17,"1,413",15.7,1,0,1,0,0,5,0,0.06,0.00,0.06,0.06,0.06,Matches

In [22]:
lst_df[1] = lst_df[1].drop('Matches', axis=1)

In [23]:
df_players = pd.concat(lst_df)
df_players.head()

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
0,1,Marcos Acuña,ar ARG,DF,Sevilla,31-047,1991,10,7,551,6.1,0,0,0,0,0,4,1,0.00,0.00,0.00,0.00,0.00
1,2,Álvaro Aguado,es ESP,MF,Valladolid,26-227,1996,13,8,747,8.3,0,2,0,0,0,1,0,0.00,0.24,0.24,0.00,0.24
2,3,Joseph Aidoo,gh GHA,DF,Celta Vigo,27-076,1995,14,14,"1,260",14.0,1,0,1,0,0,2,0,0.07,0.00,0.07,0.07,0.07
3,4,Sergio Akieme,es ESP,DF,Almería,24-363,1997,14,14,"1,260",14.0,0,0,0,0,0,3,0,0.00,0.00,0.00,0.00,0.00
4,5,Paul Akouokou,ci CIV,MF,Betis,24-359,1997,6,2,238,2.6,0,0,0,0,0,2,0,0.00,0.00,0.00,0.00,0.00

In [24]:
df_players.reset_index(drop=True, inplace=True)
df_players.tail()

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
1105,567,Ekain Zenitagoia,es ESP,FW,UD Ibiza,28-347,1994,19,15,"1,297",14.4,2,2,1,1,1,4,0,0.14,0.14,0.28,0.07,0.21
1106,568,Luca Zidane,fr FRA,GK,Eibar,24-215,1998,9,9,810,9.0,0,0,0,0,0,2,0,0.00,0.00,0.00,0.00,0.00
1107,569,Elady Zorrilla,es ESP,"MF,FW",Tenerife,32-154,1990,7,2,308,3.4,2,0,0,2,2,1,0,0.58,0.00,0.58,0.00,0.00
1108,570,Loren Zúñiga,es ESP,FW,Málaga,19-330,2003,13,2,364,4.0,0,0,0,0,0,3,0,0.00,0.00,0.00,0.00,0.00
1109,571,Uroš Đurđević,me MNE,FW,Sporting Gijón,28-287,1994,18,13,"1,161",12.9,2,1,2,0,0,3,0,0.16,0.08,0.23,0.16,0.23

In [25]:
df_players = df_players.drop('Rk', axis=1)
df_players.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
0,Marcos Acuña,ar ARG,DF,Sevilla,31-047,1991,10,7,551,6.1,0,0,0,0,0,4,1,0.00,0.00,0.00,0.00,0.00
1,Álvaro Aguado,es ESP,MF,Valladolid,26-227,1996,13,8,747,8.3,0,2,0,0,0,1,0,0.00,0.24,0.24,0.00,0.24
2,Joseph Aidoo,gh GHA,DF,Celta Vigo,27-076,1995,14,14,"1,260",14.0,1,0,1,0,0,2,0,0.07,0.00,0.07,0.07,0.07
3,Sergio Akieme,es ESP,DF,Almería,24-363,1997,14,14,"1,260",14.0,0,0,0,0,0,3,0,0.00,0.00,0.00,0.00,0.00
4,Paul Akouokou,ci CIV,MF,Betis,24-359,1997,6,2,238,2.6,0,0,0,0,0,2,0,0.00,0.00,0.00,0.00,0.00

In [26]:
print("Saving csv")
df_players.to_csv(r'../data/players.csv')
print("File Saved")

Saving csv
File Saved

### ESTADIOS

In [ ]:
url = 'https://hmong.es/wiki/List_of_stadiums_in_Spain'

In [ ]:
estadios = ex.scraping_estadios(url)

In [ ]:
estadios.head()

In [ ]:
print("Saving csv")
estadios.to_csv(r'../data/stadiums.csv')
print("File Saved")