In [1]:
import numpy as np
import pandas as pd
from datetime import datetime as dt
import itertools

%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('../data_limpio/matches_l.csv')
data.head()

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25

In [3]:
def goles(season2223_1):
    teams = {}
    for i in season2223_1.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    #print(teams, len(teams))

    for i in range(len(season2223_1)):
        ATGC = season2223_1.iloc[i]['FTHG']
        HTGC = season2223_1.iloc[i]['FTAG']
        teams[season2223_1.iloc[i].HomeTeam].append(HTGC)
        teams[season2223_1.iloc[i].AwayTeam].append(ATGC)
    #print(teams, len(list(teams.values())[0]))

    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,len(list(teams.values())[0])+1)]).T
    GoalsConceded[0] = 0

    for i in range(2,len(list(teams.values())[0])+1):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    GoalsConceded
    teams = {}
    for i in season2223_1.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    #print(teams, len(teams))

    for i in range(len(season2223_1)):
        HTGS = season2223_1.iloc[i]['FTHG']
        ATGS = season2223_1.iloc[i]['FTAG']
        teams[season2223_1.iloc[i].HomeTeam].append(HTGS)
        teams[season2223_1.iloc[i].AwayTeam].append(ATGS)
    #print(teams, len(list(teams.values())[0]))

    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,len(list(teams.values())[0])+1)]).T
    GoalsScored[0] = 0

    for i in range(2,len(list(teams.values())[0])+1):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    GoalsScored
    season2223_1 = season2223_1.sort_values(by='Id',ascending=False)
    j = 0
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []
    for i in range(len(season2223_1)):
        ht = season2223_1.iloc[i].HomeTeam
        at = season2223_1.iloc[i].AwayTeam
        HTGS.append(GoalsScored.loc[ht][j])
        ATGS.append(GoalsScored.loc[at][j])
        HTGC.append(GoalsConceded.loc[ht][j])
        ATGC.append(GoalsConceded.loc[at][j])
        
        if ((i + 1)% 11) == 0 and len(teams) == 22:
            j = j + 1
        elif ((i + 1)% 10) == 0 and len(teams) == 20:
            j = j + 1

    season2223_1['HTGS'] = HTGS
    season2223_1['ATGS'] = ATGS
    season2223_1['HTGC'] = HTGC
    season2223_1['ATGC'] = ATGC

    season2223_1 = season2223_1.sort_values(by='Id',ascending=True)
    print('Completada')
    print('Temporada: ' + str(season2223_1.Season.unique()) + ', división: ' + season2223_1.Div.unique())
    return season2223_1

In [4]:
lista = []
for x in list(data.Div.unique()):
    for e in list(data.Season.unique()):
        lista.append(goles(data[(data.Div == x) & (data.Season == e)]))
df = pd.concat(lista)
df.head()

Completada
['Temporada: [2223], división: SP2']
Completada
['Temporada: [2122], división: SP2']
Completada
['Temporada: [2021], división: SP2']
Completada
['Temporada: [1920], división: SP2']
Completada
['Temporada: [1819], división: SP2']
Completada
['Temporada: [1718], división: SP2']
Completada
['Temporada: [1617], división: SP2']
Completada
['Temporada: [1516], división: SP2']
Completada
['Temporada: [1415], división: SP2']
Completada
['Temporada: [1314], división: SP2']
Completada
['Temporada: [1213], división: SP2']
Completada
['Temporada: [1112], división: SP2']
Completada
['Temporada: [1011], división: SP2']
Completada
['Temporada: [910], división: SP2']
Completada
['Temporada: [89], división: SP2']
Completada
['Temporada: [78], división: SP2']
Completada
['Temporada: [67], división: SP2']
Completada
['Temporada: [56], división: SP2']
Completada
['Temporada: [2223], división: SP1']
Completada
['Temporada: [2122], división: SP1']
Completada
['Temporada: [2021], división: SP1']
Completada
['Temporada: [1920], división: SP1']
Completada
['Temporada: [1819], división: SP1']
Completada
['Temporada: [1718], división: SP1']
Completada
['Temporada: [1617], división: SP1']
Completada
['Temporada: [1516], división: SP1']
Completada
['Temporada: [1415], división: SP1']
Completada
['Temporada: [1314], división: SP1']
Completada
['Temporada: [1213], división: SP1']
Completada
['Temporada: [1112], división: SP1']
Completada
['Temporada: [1011], división: SP1']
Completada
['Temporada: [910], división: SP1']
Completada
['Temporada: [89], división: SP1']
Completada
['Temporada: [78], división: SP1']
Completada
['Temporada: [67], división: SP1']
Completada
['Temporada: [56], división: SP1']

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25

In [5]:
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0

match_point = pd.DataFrame()
teams = {}
def get_mp(sesion):
    global teams
    teams = {}
    for i in sesion.groupby('HomeTeam').mean().T.columns:
        teams[i] = []

    for i in range(len(sesion)):
        if sesion.iloc[i].FTR == 'H':
            teams[sesion.iloc[i].HomeTeam].append('W')
            teams[sesion.iloc[i].AwayTeam].append('L')
        elif sesion.iloc[i].FTR == 'A':
            teams[sesion.iloc[i].AwayTeam].append('W')
            teams[sesion.iloc[i].HomeTeam].append('L')
        else:
            teams[sesion.iloc[i].AwayTeam].append('D')
            teams[sesion.iloc[i].HomeTeam].append('D')
    
    tabwl = pd.DataFrame(data=teams, index = [i for i in range(1,len(list(teams.values())[0])+1)]).T
    return tabwl

In [6]:
def points(sesion):
    global match_point
    
    tabwl = get_mp(sesion)
    matchres_points = tabwl.applymap(get_points)
    for i in range(2,len(list(teams.values())[0])+1):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]

    matchres_points.insert(column =0, loc = 0, value = [0*i for i in range(len(teams))])
    match_point = matchres_points
    
    sesion = sesion.sort_values(by='Id',ascending=False)
    HTP = []
    ATP = []
    j = 0
    for i in range(len(sesion)):
        ht = sesion.iloc[i].HomeTeam
        at = sesion.iloc[i].AwayTeam
        HTP.append(matchres_points.loc[ht][j])
        ATP.append(matchres_points.loc[at][j])

        if ((i + 1)% 11) == 0 and len(teams) == 22:
                j = j + 1
        elif ((i + 1)% 10) == 0 and len(teams) == 20:
            j = j + 1

    sesion['HTP'] = HTP
    sesion['ATP'] = ATP
    sesion = sesion.sort_values(by='Id',ascending=True)
    print('Completada')
    print('Temporada: ' + str(sesion.Season.unique()) + ', división: ' + sesion.Div.unique())
    return sesion

In [7]:
lista = []
for x in list(data.Div.unique()):
    for e in list(data.Season.unique()):
        lista.append(points(df[(df.Div == x) & (df.Season == e)]))
df = pd.concat(lista)
df.head()

Completada
['Temporada: [2223], división: SP2']
Completada
['Temporada: [2122], división: SP2']
Completada
['Temporada: [2021], división: SP2']
Completada
['Temporada: [1920], división: SP2']
Completada
['Temporada: [1819], división: SP2']
Completada
['Temporada: [1718], división: SP2']
Completada
['Temporada: [1617], división: SP2']
Completada
['Temporada: [1516], división: SP2']
Completada
['Temporada: [1415], división: SP2']
Completada
['Temporada: [1314], división: SP2']
Completada
['Temporada: [1213], división: SP2']
Completada
['Temporada: [1112], división: SP2']
Completada
['Temporada: [1011], división: SP2']
Completada
['Temporada: [910], división: SP2']
Completada
['Temporada: [89], división: SP2']
Completada
['Temporada: [78], división: SP2']
Completada
['Temporada: [67], división: SP2']
Completada
['Temporada: [56], división: SP2']
Completada
['Temporada: [2223], división: SP1']
Completada
['Temporada: [2122], división: SP1']
Completada
['Temporada: [2021], división: SP1']
Completada
['Temporada: [1920], división: SP1']
Completada
['Temporada: [1819], división: SP1']
Completada
['Temporada: [1718], división: SP1']
Completada
['Temporada: [1617], división: SP1']
Completada
['Temporada: [1516], división: SP1']
Completada
['Temporada: [1415], división: SP1']
Completada
['Temporada: [1314], división: SP1']
Completada
['Temporada: [1213], división: SP1']
Completada
['Temporada: [1112], división: SP1']
Completada
['Temporada: [1011], división: SP1']
Completada
['Temporada: [910], división: SP1']
Completada
['Temporada: [89], división: SP1']
Completada
['Temporada: [78], división: SP1']
Completada
['Temporada: [67], división: SP1']
Completada
['Temporada: [56], división: SP1']

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22

In [8]:
def get_form(playing_stat,num):
    form = get_matchres(playing_stat)
    form_final = form.copy()
    for i in range(num,39):
        form_final[i] = ''
        j = 0
        while j < num:
            form_final[i] += form[i-j]
            j += 1           
    return form_final

In [9]:
def add_form(playing_stat,num):
    form = get_form(playing_stat,num)
    h = ['M' for i in range(num * 10)]  # since form is not available for n MW (n*10)
    a = ['M' for i in range(num * 10)]
    
    j = num
    for i in range((num*10),380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        
        past = form.loc[ht][j]               # get past n results
        h.append(past[num-1])                    # 0 index is most recent
        
        past = form.loc[at][j]               # get past n results.
        a.append(past[num-1])                   # 0 index is most recent
        
        if ((i + 1)% 10) == 0:
            j = j + 1

    playing_stat['HM' + str(num)] = h                 
    playing_stat['AM' + str(num)] = a

    
    return playing_stat

In [10]:
def add_form_df(playing_statistics):
    playing_statistics = add_form(playing_statistics,1)
    playing_statistics = add_form(playing_statistics,2)
    playing_statistics = add_form(playing_statistics,3)
    playing_statistics = add_form(playing_statistics,4)
    playing_statistics = add_form(playing_statistics,5)
    return playing_statistics

In [11]:
sesion = df[(df.Div == 'SP2') & (df.Season == 2223)]
sesion

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.00,3.25,2.40,2.95,2.90,2223,20,31,20,22,18,13,31,34
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.30,5.00,1.75,3.25,4.60,2223,29,21,23,21,12,24,34,26
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.30,3.25,2.20,3.20,3.00,2223,35,32,16,16,25,24,18,18
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.00,3.40,2.25,2.95,3.20,2223,39,33,14,15,26,24,16,16
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.10,4.00,2.10,2.95,3.50,2223,36,25,10,22,15,25,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,352,SP2,2022-08-13,CD Mirandes,Sporting Gijon,1,1,D,1,1,D,15,8,2,4,16,5,3,2,1,2,0,0,2.60,3.25,2.70,2.60,3.10,2.55,2223,25,37,0,0,0,0,0,0
353,353,SP2,2022-08-13,Leganes,Alaves,1,2,A,0,1,A,15,9,2,3,11,14,3,3,3,3,0,0,2.62,3.25,2.70,2.50,3.00,2.65,2223,30,20,0,0,0,0,0,0
354,354,SP2,2022-08-13,Las Palmas,Zaragoza,0,0,D,0,0,D,12,8,5,3,11,20,4,2,5,3,0,0,1.95,3.40,4.20,1.90,3.20,3.70,2223,29,41,0,0,0,0,0,0
357,357,SP2,2022-08-13,Eibar,Tenerife,2,1,H,0,0,D,12,6,3,1,15,6,6,4,4,2,0,0,2.05,3.20,4.00,1.98,2.95,3.80,2223,26,38,0,0,0,0,0,0
359,359,SP2,2022-08-12,Levante,Huesca,0,0,D,0,0,D,16,9,2,2,19,9,10,2,3,1,0,0,1.60,3.75,6.00,1.55,3.60,5.25,2223,31,28,0,0,0,0,0,0

In [12]:
def forma(sesion, num):
    form = get_mp(sesion)
    form_final = form.copy()
    for i in range(num,len(form.columns)+1):
        form_final[i] = ''
        j = 0
        while j < num:
            form_final[i] += form[i-j]
            j += 1           
    form_final
    if sesion.Div.iloc[0] == 'SP1':
        sesion = sesion.sort_values(by='Id',ascending=False)
        h = ['M' for i in range(num * 10)]  # since form is not available for n MW (n*10)
        a = ['M' for i in range(num * 10)]
        j = num
        for i in range((num*10),len(sesion)):
            ht = sesion.iloc[i].HomeTeam
            at = sesion.iloc[i].AwayTeam

            past = form_final.loc[ht][j]               # get past n results
            h.append(past[num-1])                    # 0 index is most recent

            past = form_final.loc[at][j]               # get past n results.
            a.append(past[num-1])                   # 0 index is most recent

            if ((i + 1)% 11) == 0 and len(teams) == 22:
                        j = j + 1
            elif ((i + 1)% 10) == 0 and len(teams) == 20:
                j = j + 1
    else:
        sesion = sesion.sort_values(by='Id',ascending=False)
        h = ['M' for i in range(num * 11)]  # since form is not available for n MW (n*10)
        a = ['M' for i in range(num * 11)]
        j = num
        for i in range((num*11),len(sesion)):
            ht = sesion.iloc[i].HomeTeam
            at = sesion.iloc[i].AwayTeam

            past = form_final.loc[ht][j]               # get past n results
            h.append(past[num-1])                    # 0 index is most recent

            past = form_final.loc[at][j]               # get past n results.
            a.append(past[num-1])                   # 0 index is most recent

            if ((i + 1)% 11) == 0 and len(teams) == 22:
                        j = j + 1
            elif ((i + 1)% 10) == 0 and len(teams) == 20:
                j = j + 1

    sesion['HM' + str(num)] = h                 
    sesion['AM' + str(num)] = a
    sesion = sesion.sort_values(by='Id',ascending=True)
    print('Completada')
    print('Temporada: ' + str(sesion.Season.unique()) + ', división: ' + sesion.Div.unique())
    return sesion

In [13]:
lista = []
for x in list(data.Div.unique()):
    for e in list(data.Season.unique()):
        lista.append(forma(df[(df.Div == x) & (df.Season == e)], 1))
df = pd.concat(lista)
lista = []
for x in list(data.Div.unique()):
    for e in list(data.Season.unique()):
        lista.append(forma(df[(df.Div == x) & (df.Season == e)], 2))
df = pd.concat(lista)
lista = []
for x in list(data.Div.unique()):
    for e in list(data.Season.unique()):
        lista.append(forma(df[(df.Div == x) & (df.Season == e)], 3))
df = pd.concat(lista)
lista = []
for x in list(data.Div.unique()):
    for e in list(data.Season.unique()):
        lista.append(forma(df[(df.Div == x) & (df.Season == e)], 4))
df = pd.concat(lista)
lista = []
for x in list(data.Div.unique()):
    for e in list(data.Season.unique()):
        lista.append(forma(df[(df.Div == x) & (df.Season == e)], 5))
df = pd.concat(lista)
df.head()

Completada
['Temporada: [2223], división: SP2']
Completada
['Temporada: [2122], división: SP2']
Completada
['Temporada: [2021], división: SP2']
Completada
['Temporada: [1920], división: SP2']
Completada
['Temporada: [1819], división: SP2']
Completada
['Temporada: [1718], división: SP2']
Completada
['Temporada: [1617], división: SP2']
Completada
['Temporada: [1516], división: SP2']
Completada
['Temporada: [1415], división: SP2']
Completada
['Temporada: [1314], división: SP2']
Completada
['Temporada: [1213], división: SP2']
Completada
['Temporada: [1112], división: SP2']
Completada
['Temporada: [1011], división: SP2']
Completada
['Temporada: [910], división: SP2']
Completada
['Temporada: [89], división: SP2']
Completada
['Temporada: [78], división: SP2']
Completada
['Temporada: [67], división: SP2']
Completada
['Temporada: [56], división: SP2']
Completada
['Temporada: [2223], división: SP1']
Completada
['Temporada: [2122], división: SP1']
Completada
['Temporada: [2021], división: SP1']
Completada
['Temporada: [1920], división: SP1']
Completada
['Temporada: [1819], división: SP1']
Completada
['Temporada: [1718], división: SP1']
Completada
['Temporada: [1617], división: SP1']
Completada
['Temporada: [1516], división: SP1']
Completada
['Temporada: [1415], división: SP1']
Completada
['Temporada: [1314], división: SP1']
Completada
['Temporada: [1213], división: SP1']
Completada
['Temporada: [1112], división: SP1']
Completada
['Temporada: [1011], división: SP1']
Completada
['Temporada: [910], división: SP1']
Completada
['Temporada: [89], división: SP1']
Completada
['Temporada: [78], división: SP1']
Completada
['Temporada: [67], división: SP1']
Completada
['Temporada: [56], división: SP1']
Completada
['Temporada: [2223], división: SP2']
Completada
['Temporada: [2122], división: SP2']
Completada
['Temporada: [2021], división: SP2']
Completada
['Temporada: [1920], división: SP2']
Completada
['Temporada: [1819], división: SP2']
Completada
['Temporada: [1718], división: SP2']
Completada
['Temporada: [1617], división: SP2']
Completada
['Temporada: [1516], división: SP2']
Completada
['Temporada: [1415], división: SP2']
Completada
['Temporada: [1314], división: SP2']
Completada
['Temporada: [1213], división: SP2']
Completada
['Temporada: [1112], división: SP2']
Completada
['Temporada: [1011], división: SP2']
Completada
['Temporada: [910], división: SP2']
Completada
['Temporada: [89], división: SP2']
Completada
['Temporada: [78], división: SP2']
Completada
['Temporada: [67], división: SP2']
Completada
['Temporada: [56], división: SP2']
Completada
['Temporada: [2223], división: SP1']
Completada
['Temporada: [2122], división: SP1']
Completada
['Temporada: [2021], división: SP1']
Completada
['Temporada: [1920], división: SP1']
Completada
['Temporada: [1819], división: SP1']
Completada
['Temporada: [1718], división: SP1']
Completada
['Temporada: [1617], división: SP1']
Completada
['Temporada: [1516], división: SP1']
Completada
['Temporada: [1415], división: SP1']
Completada
['Temporada: [1314], división: SP1']
Completada
['Temporada: [1213], división: SP1']
Completada
['Temporada: [1112], división: SP1']
Completada
['Temporada: [1011], división: SP1']
Completada
['Temporada: [910], división: SP1']
Completada
['Temporada: [89], división: SP1']
Completada
['Temporada: [78], división: SP1']
Completada
['Temporada: [67], división: SP1']
Completada
['Temporada: [56], división: SP1']
Completada
['Temporada: [2223], división: SP2']
Completada
['Temporada: [2122], división: SP2']
Completada
['Temporada: [2021], división: SP2']
Completada
['Temporada: [1920], división: SP2']
Completada
['Temporada: [1819], división: SP2']
Completada
['Temporada: [1718], división: SP2']
Completada
['Temporada: [1617], división: SP2']
Completada
['Temporada: [1516], división: SP2']
Completada
['Temporada: [1415], división: SP2']
Completada
['Temporada: [1314], división: SP2']
Completada
['Temporada: [1213], división: SP2']
Completada
['Temporada: [1112], división: SP2']
Completada
['Temporada: [1011], división: SP2']
Completada
['Temporada: [910], división: SP2']
Completada
['Temporada: [89], división: SP2']
Completada
['Temporada: [78], división: SP2']
Completada
['Temporada: [67], división: SP2']
Completada
['Temporada: [56], división: SP2']
Completada
['Temporada: [2223], división: SP1']
Completada
['Temporada: [2122], división: SP1']
Completada
['Temporada: [2021], división: SP1']
Completada
['Temporada: [1920], división: SP1']
Completada
['Temporada: [1819], división: SP1']
Completada
['Temporada: [1718], división: SP1']
Completada
['Temporada: [1617], división: SP1']
Completada
['Temporada: [1516], división: SP1']
Completada
['Temporada: [1415], división: SP1']
Completada
['Temporada: [1314], división: SP1']
Completada
['Temporada: [1213], división: SP1']
Completada
['Temporada: [1112], división: SP1']
Completada
['Temporada: [1011], división: SP1']
Completada
['Temporada: [910], división: SP1']
Completada
['Temporada: [89], división: SP1']
Completada
['Temporada: [78], división: SP1']
Completada
['Temporada: [67], división: SP1']
Completada
['Temporada: [56], división: SP1']
Completada
['Temporada: [2223], división: SP2']
Completada
['Temporada: [2122], división: SP2']
Completada
['Temporada: [2021], división: SP2']
Completada
['Temporada: [1920], división: SP2']
Completada
['Temporada: [1819], división: SP2']
Completada
['Temporada: [1718], división: SP2']
Completada
['Temporada: [1617], división: SP2']
Completada
['Temporada: [1516], división: SP2']
Completada
['Temporada: [1415], división: SP2']
Completada
['Temporada: [1314], división: SP2']
Completada
['Temporada: [1213], división: SP2']
Completada
['Temporada: [1112], división: SP2']
Completada
['Temporada: [1011], división: SP2']
Completada
['Temporada: [910], división: SP2']
Completada
['Temporada: [89], división: SP2']
Completada
['Temporada: [78], división: SP2']
Completada
['Temporada: [67], división: SP2']
Completada
['Temporada: [56], división: SP2']
Completada
['Temporada: [2223], división: SP1']
Completada
['Temporada: [2122], división: SP1']
Completada
['Temporada: [2021], división: SP1']
Completada
['Temporada: [1920], división: SP1']
Completada
['Temporada: [1819], división: SP1']
Completada
['Temporada: [1718], división: SP1']
Completada
['Temporada: [1617], división: SP1']
Completada
['Temporada: [1516], división: SP1']
Completada
['Temporada: [1415], división: SP1']
Completada
['Temporada: [1314], división: SP1']
Completada
['Temporada: [1213], división: SP1']
Completada
['Temporada: [1112], división: SP1']
Completada
['Temporada: [1011], división: SP1']
Completada
['Temporada: [910], división: SP1']
Completada
['Temporada: [89], división: SP1']
Completada
['Temporada: [78], división: SP1']
Completada
['Temporada: [67], división: SP1']
Completada
['Temporada: [56], división: SP1']
Completada
['Temporada: [2223], división: SP2']
Completada
['Temporada: [2122], división: SP2']
Completada
['Temporada: [2021], división: SP2']
Completada
['Temporada: [1920], división: SP2']
Completada
['Temporada: [1819], división: SP2']
Completada
['Temporada: [1718], división: SP2']
Completada
['Temporada: [1617], división: SP2']
Completada
['Temporada: [1516], división: SP2']
Completada
['Temporada: [1415], división: SP2']
Completada
['Temporada: [1314], división: SP2']
Completada
['Temporada: [1213], división: SP2']
Completada
['Temporada: [1112], división: SP2']
Completada
['Temporada: [1011], división: SP2']
Completada
['Temporada: [910], división: SP2']
Completada
['Temporada: [89], división: SP2']
Completada
['Temporada: [78], división: SP2']
Completada
['Temporada: [67], división: SP2']
Completada
['Temporada: [56], división: SP2']
Completada
['Temporada: [2223], división: SP1']
Completada
['Temporada: [2122], división: SP1']
Completada
['Temporada: [2021], división: SP1']
Completada
['Temporada: [1920], división: SP1']
Completada
['Temporada: [1819], división: SP1']
Completada
['Temporada: [1718], división: SP1']
Completada
['Temporada: [1617], división: SP1']
Completada
['Temporada: [1516], división: SP1']
Completada
['Temporada: [1415], división: SP1']
Completada
['Temporada: [1314], división: SP1']
Completada
['Temporada: [1213], división: SP1']

Completada
['Temporada: [1112], división: SP1']
Completada
['Temporada: [1011], división: SP1']
Completada
['Temporada: [910], división: SP1']
Completada
['Temporada: [89], división: SP1']
Completada
['Temporada: [78], división: SP1']
Completada
['Temporada: [67], división: SP1']
Completada
['Temporada: [56], división: SP1']

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34,W,D,D,W,D,D,W,W,W,L
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26,W,D,W,W,D,W,W,L,D,L
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18,W,D,L,W,L,W,L,L,W,L
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16,L,L,D,W,L,L,W,L,W,L
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22,L,L,L,L,L,L,W,D,D,L

In [14]:
def get_f_p(string):
    sum = 0
    for letter in string:
        sum += get_points(letter)
    return sum

In [15]:
df['HTFormPtsStr'] = df['HM1'] + df['HM2'] + df['HM3'] + df['HM4'] + df['HM5']
df['ATFormPtsStr'] = df['AM1'] + df['AM2'] + df['AM3'] + df['AM4'] + df['AM5']

df['HTFormPts'] = df['HTFormPtsStr'].apply(get_f_p)
df['ATFormPts'] = df['ATFormPtsStr'].apply(get_f_p)

df.head()

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34,W,D,D,W,D,D,W,W,W,L,WDDWW,DWDWL,11,8
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26,W,D,W,W,D,W,W,L,D,L,WWDWD,DWWLL,11,7
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18,W,D,L,W,L,W,L,L,W,L,WLLLW,DWWLL,6,7
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16,L,L,D,W,L,L,W,L,W,L,LDLWW,LWLLL,7,3
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22,L,L,L,L,L,L,W,D,D,L,LLLWD,LLLDL,4,1

In [16]:
def get_3w(s):
    if s[-3:] == 'WWW':
        return 1
    else:
        return 0
    
def get_5w(s):
    if s == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3l(s):
    if s[-3:] == 'LLL':
        return 1
    else:
        return 0
    
def get_5l(s):
    if s == 'LLLLL':
        return 1
    else:
        return 0

In [17]:
df['HTWin3'] = df['HTFormPtsStr'].apply(get_3w)
df['HTWin5'] = df['HTFormPtsStr'].apply(get_5w)
df['HTLoss3'] = df['HTFormPtsStr'].apply(get_3l)
df['HTLoss5'] = df['HTFormPtsStr'].apply(get_5l)

df['ATWin3'] = df['ATFormPtsStr'].apply(get_3w)
df['ATWin5'] = df['ATFormPtsStr'].apply(get_5w)
df['ATLoss3'] = df['ATFormPtsStr'].apply(get_3l)
df['ATLoss5'] = df['ATFormPtsStr'].apply(get_5l)

df.head()

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts,HTWin3,HTWin5,HTLoss3,HTLoss5,ATWin3,ATWin5,ATLoss3,ATLoss5
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34,W,D,D,W,D,D,W,W,W,L,WDDWW,DWDWL,11,8,0,0,0,0,0,0,0,0
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26,W,D,W,W,D,W,W,L,D,L,WWDWD,DWWLL,11,7,0,0,0,0,0,0,0,0
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18,W,D,L,W,L,W,L,L,W,L,WLLLW,DWWLL,6,7,0,0,0,0,0,0,0,0
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16,L,L,D,W,L,L,W,L,W,L,LDLWW,LWLLL,7,3,0,0,0,0,0,0,1,0
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22,L,L,L,L,L,L,W,D,D,L,LLLWD,LLLDL,4,1,0,0,0,0,0,0,0,0

In [18]:
df['HTDG'] = df['HTGS'] - df['HTGC']
df['ATDG'] = df['ATGS'] - df['ATGC']

df.head()

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts,HTWin3,HTWin5,HTLoss3,HTLoss5,ATWin3,ATWin5,ATLoss3,ATLoss5,HTDG,ATDG
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34,W,D,D,W,D,D,W,W,W,L,WDDWW,DWDWL,11,8,0,0,0,0,0,0,0,0,2,9
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26,W,D,W,W,D,W,W,L,D,L,WWDWD,DWWLL,11,7,0,0,0,0,0,0,0,0,11,-3
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18,W,D,L,W,L,W,L,L,W,L,WLLLW,DWWLL,6,7,0,0,0,0,0,0,0,0,-9,-8
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16,L,L,D,W,L,L,W,L,W,L,LDLWW,LWLLL,7,3,0,0,0,0,0,0,1,0,-12,-9
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22,L,L,L,L,L,L,W,D,D,L,LLLWD,LLLDL,4,1,0,0,0,0,0,0,0,0,-5,-3

In [19]:
df['DiffPts'] = df['HTP'] - df['ATP']
df['DiffFormPts'] = df['HTFormPts'] - df['ATFormPts']

df.head()

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts,HTWin3,HTWin5,HTLoss3,HTLoss5,ATWin3,ATWin5,ATLoss3,ATLoss5,HTDG,ATDG,DiffPts,DiffFormPts
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34,W,D,D,W,D,D,W,W,W,L,WDDWW,DWDWL,11,8,0,0,0,0,0,0,0,0,2,9,-3,3
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26,W,D,W,W,D,W,W,L,D,L,WWDWD,DWWLL,11,7,0,0,0,0,0,0,0,0,11,-3,8,4
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18,W,D,L,W,L,W,L,L,W,L,WLLLW,DWWLL,6,7,0,0,0,0,0,0,0,0,-9,-8,0,-1
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16,L,L,D,W,L,L,W,L,W,L,LDLWW,LWLLL,7,3,0,0,0,0,0,0,1,0,-12,-9,0,4
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22,L,L,L,L,L,L,W,D,D,L,LLLWD,LLLDL,4,1,0,0,0,0,0,0,0,0,-5,-3,-4,3

In [20]:
def get_mw(playing_stat):
    j = 1
    MatchWeek = []
    for i in range(380):
        MatchWeek.append(j)
        if ((i + 1)% 10) == 0:
            j = j + 1
    playing_stat['MW'] = MatchWeek
    return playing_stat

In [21]:
sesion = df[(df.Div == 'SP2') & (df.Season == 2223)]
sesion.head()

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts,HTWin3,HTWin5,HTLoss3,HTLoss5,ATWin3,ATWin5,ATLoss3,ATLoss5,HTDG,ATDG,DiffPts,DiffFormPts
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34,W,D,D,W,D,D,W,W,W,L,WDDWW,DWDWL,11,8,0,0,0,0,0,0,0,0,2,9,-3,3
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26,W,D,W,W,D,W,W,L,D,L,WWDWD,DWWLL,11,7,0,0,0,0,0,0,0,0,11,-3,8,4
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18,W,D,L,W,L,W,L,L,W,L,WLLLW,DWWLL,6,7,0,0,0,0,0,0,0,0,-9,-8,0,-1
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16,L,L,D,W,L,L,W,L,W,L,LDLWW,LWLLL,7,3,0,0,0,0,0,0,1,0,-12,-9,0,4
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22,L,L,L,L,L,L,W,D,D,L,LLLWD,LLLDL,4,1,0,0,0,0,0,0,0,0,-5,-3,-4,3

In [22]:
len(sesion.HomeTeam.unique())

22

In [23]:
def journey(sesion):
    j = 1
    journey = []
    for i in range(len(sesion)):
        journey.append(j)
        if ((i + 1)% 11) == 0 and len(sesion.HomeTeam.unique()) == 22:
                    j = j + 1
        elif ((i + 1)% 10) == 0 and len(sesion.HomeTeam.unique()) == 20:
            j = j + 1
    sesion = sesion.sort_values(by='Id',ascending=False)
    sesion['Journey'] = journey
    sesion = sesion.sort_values(by='Id',ascending=True)
    print('Completada')
    print('Temporada: ' + str(sesion.Season.unique()) + ', división: ' + sesion.Div.unique())
    return sesion

In [24]:
lista = []
for x in list(data.Div.unique()):
    for e in list(data.Season.unique()):
        lista.append(journey(df[(df.Div == x) & (df.Season == e)]))
df = pd.concat(lista)
df.head()

Completada
['Temporada: [2223], división: SP2']
Completada
['Temporada: [2122], división: SP2']
Completada
['Temporada: [2021], división: SP2']
Completada
['Temporada: [1920], división: SP2']
Completada
['Temporada: [1819], división: SP2']
Completada
['Temporada: [1718], división: SP2']
Completada
['Temporada: [1617], división: SP2']
Completada
['Temporada: [1516], división: SP2']
Completada
['Temporada: [1415], división: SP2']
Completada
['Temporada: [1314], división: SP2']
Completada
['Temporada: [1213], división: SP2']
Completada
['Temporada: [1112], división: SP2']
Completada
['Temporada: [1011], división: SP2']
Completada
['Temporada: [910], división: SP2']
Completada
['Temporada: [89], división: SP2']
Completada
['Temporada: [78], división: SP2']
Completada
['Temporada: [67], división: SP2']
Completada
['Temporada: [56], división: SP2']
Completada
['Temporada: [2223], división: SP1']
Completada
['Temporada: [2122], división: SP1']
Completada
['Temporada: [2021], división: SP1']
Completada
['Temporada: [1920], división: SP1']
Completada
['Temporada: [1819], división: SP1']
Completada
['Temporada: [1718], división: SP1']
Completada
['Temporada: [1617], división: SP1']
Completada
['Temporada: [1516], división: SP1']
Completada
['Temporada: [1415], división: SP1']
Completada
['Temporada: [1314], división: SP1']
Completada
['Temporada: [1213], división: SP1']
Completada
['Temporada: [1112], división: SP1']
Completada
['Temporada: [1011], división: SP1']
Completada
['Temporada: [910], división: SP1']
Completada
['Temporada: [89], división: SP1']
Completada
['Temporada: [78], división: SP1']
Completada
['Temporada: [67], división: SP1']
Completada
['Temporada: [56], división: SP1']

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts,HTWin3,HTWin5,HTLoss3,HTLoss5,ATWin3,ATWin5,ATLoss3,ATLoss5,HTDG,ATDG,DiffPts,DiffFormPts,Journey
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34,W,D,D,W,D,D,W,W,W,L,WDDWW,DWDWL,11,8,0,0,0,0,0,0,0,0,2,9,-3,3,20
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26,W,D,W,W,D,W,W,L,D,L,WWDWD,DWWLL,11,7,0,0,0,0,0,0,0,0,11,-3,8,4,20
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18,W,D,L,W,L,W,L,L,W,L,WLLLW,DWWLL,6,7,0,0,0,0,0,0,0,0,-9,-8,0,-1,20
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16,L,L,D,W,L,L,W,L,W,L,LDLWW,LWLLL,7,3,0,0,0,0,0,0,1,0,-12,-9,0,4,20
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22,L,L,L,L,L,L,W,D,D,L,LLLWD,LLLDL,4,1,0,0,0,0,0,0,0,0,-5,-3,-4,3,20

In [25]:
df[['HTDG','ATDG','DiffPts','DiffFormPts','HTP','ATP']].head()

   HTDG  ATDG  DiffPts  DiffFormPts  HTP  ATP
0     2     9       -3            3   31   34
1    11    -3        8            4   34   26
2    -9    -8        0           -1   18   18
3   -12    -9        0            4   16   16
4    -5    -3       -4            3   18   22

In [26]:
med_cols = ['Med_HTDG','Med_ATDG','Med_DiffPts','Med_DiffFormPts','Med_HTP','Med_ATP',
            'Med_HTGS', 'Med_ATGS', 'Med_HTGC', 'Med_ATGC']

df['Med_HTDG'] = df['HTDG'] / df.Journey
df['Med_ATDG'] = df['ATDG'] / df.Journey
df['Med_DiffPts'] = df['DiffPts'] / df.Journey
df['Med_DiffFormPts'] = df['DiffFormPts'] / df.Journey
df['Med_HTP'] = df['HTP'] / df.Journey
df['Med_ATP'] = df['ATP'] / df.Journey
df['Med_HTGS'] = df['HTGS'] / df.Journey
df['Med_ATGS'] = df['ATGS'] / df.Journey
df['Med_HTGC'] = df['HTGC'] / df.Journey
df['Med_ATGC'] = df['ATGC'] / df.Journey
df.head()

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts,HTWin3,HTWin5,HTLoss3,HTLoss5,ATWin3,ATWin5,ATLoss3,ATLoss5,HTDG,ATDG,DiffPts,DiffFormPts,Journey,Med_HTDG,Med_ATDG,Med_DiffPts,Med_DiffFormPts,Med_HTP,Med_ATP,Med_HTGS,Med_ATGS,Med_HTGC,Med_ATGC
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34,W,D,D,W,D,D,W,W,W,L,WDDWW,DWDWL,11,8,0,0,0,0,0,0,0,0,2,9,-3,3,20,0.10,0.45,-0.15,0.15,1.55,1.7,1.00,1.10,0.90,0.65
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26,W,D,W,W,D,W,W,L,D,L,WWDWD,DWWLL,11,7,0,0,0,0,0,0,0,0,11,-3,8,4,20,0.55,-0.15,0.40,0.20,1.70,1.3,1.15,1.05,0.60,1.20
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18,W,D,L,W,L,W,L,L,W,L,WLLLW,DWWLL,6,7,0,0,0,0,0,0,0,0,-9,-8,0,-1,20,-0.45,-0.40,0.00,-0.05,0.90,0.9,0.80,0.80,1.25,1.20
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16,L,L,D,W,L,L,W,L,W,L,LDLWW,LWLLL,7,3,0,0,0,0,0,0,1,0,-12,-9,0,4,20,-0.60,-0.45,0.00,0.20,0.80,0.8,0.70,0.75,1.30,1.20
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22,L,L,L,L,L,L,W,D,D,L,LLLWD,LLLDL,4,1,0,0,0,0,0,0,0,0,-5,-3,-4,3,20,-0.25,-0.15,-0.20,0.15,0.90,1.1,0.50,1.10,0.75,1.25

In [27]:
def home_or_not(string):
    if string == 'H':
        return 'H'
    else:
        return 'NH'

In [28]:
df['FTR_h_or_not'] = df.FTR.apply(home_or_not)

df.head()

,Id,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,Season,Id_HomeTeam,Id_AwayTeam,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HTFormPtsStr,ATFormPtsStr,HTFormPts,ATFormPts,HTWin3,HTWin5,HTLoss3,HTLoss5,ATWin3,ATWin5,ATLoss3,ATLoss5,HTDG,ATDG,DiffPts,DiffFormPts,Journey,Med_HTDG,Med_ATDG,Med_DiffPts,Med_DiffFormPts,Med_HTP,Med_ATP,Med_HTGS,Med_ATGS,Med_HTGC,Med_ATGC,FTR_h_or_not
0,0,SP2,2022-12-12,Alaves,Levante,0,2,A,0,2,A,11,7,1,5,21,15,6,2,3,3,1,0,2.38,3.0,3.25,2.40,2.95,2.9,2223,20,31,20,22,18,13,31,34,W,D,D,W,D,D,W,W,W,L,WDDWW,DWDWL,11,8,0,0,0,0,0,0,0,0,2,9,-3,3,20,0.10,0.45,-0.15,0.15,1.55,1.7,1.00,1.10,0.90,0.65,NH
1,1,SP2,2022-12-11,Las Palmas,Albacete,1,2,A,0,1,A,25,12,11,7,13,16,9,5,3,3,0,0,1.80,3.3,5.00,1.75,3.25,4.6,2223,29,21,23,21,12,24,34,26,W,D,W,W,D,W,W,L,D,L,WWDWD,DWWLL,11,7,0,0,0,0,0,0,0,0,11,-3,8,4,20,0.55,-0.15,0.40,0.20,1.70,1.3,1.15,1.05,0.60,1.20,NH
2,2,SP2,2022-12-11,Ponferradina,Lugo,1,0,H,1,0,H,10,4,3,1,16,11,1,4,2,3,1,0,2.25,3.3,3.25,2.20,3.20,3.0,2223,35,32,16,16,25,24,18,18,W,D,L,W,L,W,L,L,W,L,WLLLW,DWWLL,6,7,0,0,0,0,0,0,0,0,-9,-8,0,-1,20,-0.45,-0.40,0.00,-0.05,0.90,0.9,0.80,0.80,1.25,1.20,H
3,3,SP2,2022-12-11,UD Ibiza,Malaga,1,1,D,0,1,A,6,8,3,4,14,18,4,8,3,2,0,0,2.30,3.0,3.40,2.25,2.95,3.2,2223,39,33,14,15,26,24,16,16,L,L,D,W,L,L,W,L,W,L,LDLWW,LWLLL,7,3,0,0,0,0,0,0,1,0,-12,-9,0,4,20,-0.60,-0.45,0.00,0.20,0.80,0.8,0.70,0.75,1.30,1.20,NH
4,4,SP2,2022-12-11,Racing Sant,CD Mirandes,1,2,A,1,1,D,12,6,5,4,9,11,8,2,0,0,0,0,2.10,3.1,4.00,2.10,2.95,3.5,2223,36,25,10,22,15,25,18,22,L,L,L,L,L,L,W,D,D,L,LLLWD,LLLDL,4,1,0,0,0,0,0,0,0,0,-5,-3,-4,3,20,-0.25,-0.15,-0.20,0.15,0.90,1.1,0.50,1.10,0.75,1.25,NH

In [29]:
df.to_csv("../final_match.csv", index = False)